server:
  port: 8080
spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/final_project"
    username: ""
    password: ""
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
limit: 50
