FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-project-data-provider-0.0.1-SNAPSHOT.jar demo-project-data-provider-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","demo-project-data-provider-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081